[toolchain]
anchor_version = "0.32.1"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
perpetuals = "3xG4QD5fEj8THmKVZqAGcPiVEKMaT8hR8oUbNYWqV7jX"

[programs.localnet]
perpetuals = "4vHgG27xssZKvuoSnWZZAjWJda1RoM6VWZmHk3xE22md"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 'tests/**/!(helpers)/*.ts' 'tests/*.ts'"

[test.validator]
[[test.genesis]]
address = "Bv3Fb9VjzjWGfX18QTUcVycAfeLoQ5zZN6vv2g3cTZxp"
program = "/Users/kyler/repos/examples/mgk-perp/artifacts/arcium_program_0.4.0.so"
